"""Deterministic generation of all index.md files and views/ from frontmatter."""
import datetime
from pathlib import Path

import yaml

from . import frontmatter
from .schema import RESERVED, URI_PATTERNS

MARKER = "<!-- generated by scripts/hub_index.py — do not hand-edit -->\n"


def _load_entries(root, subdir_glob):
    """Yield (rootpath, meta, body) for knowledge entries matching the glob."""
    features = root / "features"
    if not features.is_dir():
        return
    for entry in sorted(features.glob(subdir_glob)):
        if entry.name in RESERVED or not entry.is_file():
            continue
        try:
            meta, body = frontmatter.load_file(entry)
        except frontmatter.FrontmatterError:
            continue  # lint reports this; indexes skip unparseable files
        yield "/" + entry.relative_to(root).as_posix(), meta, body


def _title(meta, rootpath):
    return meta.get("title") or Path(rootpath).stem


def _line(rootpath, meta):
    return f"- [{_title(meta, rootpath)}]({rootpath}) — {meta.get('description', '')}"


def _date(value):
    try:
        return datetime.date.fromisoformat(str(value))
    except (TypeError, ValueError):
        return None


def _staleness_config(root):
    cfg = {"profile_default_days": 30, "fact_default_days": 90}
    p = root / "conventions" / "staleness.yaml"
    if p.is_file():
        loaded = yaml.safe_load(p.read_text(encoding="utf-8")) or {}
        cfg.update({k: v for k, v in loaded.items() if k in cfg})
    return cfg


def _features_table(root):
    p = root / "features" / "features.yaml"
    if not p.is_file():
        return []
    data = yaml.safe_load(p.read_text(encoding="utf-8")) or {}
    return data.get("features") or []


def _meta_of(path):
    try:
        return frontmatter.load_file(path)[0]
    except frontmatter.FrontmatterError:
        return None


def build_all(root, today=None):
    root = Path(root)
    today = today or datetime.date.today()
    built = {}
    feats = _features_table(root)

    # features/index.md
    lines = [MARKER + "# Features", ""]
    for f in feats:
        lines.append(f"- [{f.get('title', f['id'])}](/features/{f['id']}/index.md)"
                     f" — {f.get('description', '')}")
    if not feats:
        lines.append("_No feature partitions yet — hub.file creates them on first use._")
    built["features/index.md"] = "\n".join(lines) + "\n"

    # per-feature indexes (only for partitions that exist on disk)
    for f in feats:
        fdir = root / "features" / f["id"]
        if not fdir.is_dir():
            continue
        lines = [MARKER + f"# {f.get('title', f['id'])}", "", f.get("description", ""), ""]
        for sub in ("knowledge", "research", "strategy", "enablement", "work"):
            lines.append(f"- [{sub}/](/features/{f['id']}/{sub}/)")
        built[f"features/{f['id']}/index.md"] = "\n".join(lines) + "\n"

        if (fdir / "knowledge").is_dir():
            lines = [MARKER + f"# {f.get('title', f['id'])} — knowledge", ""]
            by_type = {}
            for rootpath, meta, _ in _load_entries(root, f"{f['id']}/knowledge/*.md"):
                by_type.setdefault(meta.get("type", "other"), []).append((rootpath, meta))
            for etype in sorted(by_type):
                lines.append(f"## {etype}")
                for rootpath, meta in sorted(by_type[etype]):
                    lines.append(_line(rootpath, meta))
                lines.append("")
            built[f"features/{f['id']}/knowledge/index.md"] = \
                "\n".join(lines).rstrip("\n") + "\n"

    # memory/index.md
    mem = root / "memory"
    lines = [MARKER + "# Memory index", "",
             "> Always read this first. Regenerate with `python scripts/hub_index.py`.", ""]
    profiles = sorted((mem / "profiles").glob("*.md")) if (mem / "profiles").is_dir() else []
    if profiles:
        lines.append("## Profiles (current state)")
        for p in profiles:
            meta = _meta_of(p)
            if meta:
                lines.append(f"- [{p.stem}](/{p.relative_to(root).as_posix()})"
                             f" — {meta.get('description', '')}")
        lines.append("")
    facts = sorted((mem / "facts").glob("*.md")) if (mem / "facts").is_dir() else []
    fact_metas = [( "/" + p.relative_to(root).as_posix(), _meta_of(p))
                  for p in facts if _meta_of(p)]
    fact_metas.sort(key=lambda t: str(t[1].get("timestamp", "")), reverse=True)
    if fact_metas:
        lines.append("## Recent facts")
        for rootpath, meta in fact_metas[:10]:
            lines.append(f"- [{Path(rootpath).stem}]({rootpath}) — {meta.get('description', '')}")
        lines.append("")
    log = mem / "log.md"
    if log.is_file():
        _, body = frontmatter.load_file(log)
        lines.append("## Recent log")
        current, shown = None, 0
        for raw in body.splitlines():
            if raw.startswith("## "):
                current = raw[3:].strip()
            elif raw.startswith("- ") and current and shown < 5:
                lines.append(f"- {current} — {raw[2:].strip()}")
                shown += 1
        lines.append("")
    built["memory/index.md"] = "\n".join(lines).rstrip("\n") + "\n"

    # views/
    entries = list(_load_entries(root, "*/knowledge/*.md"))
    cfg = _staleness_config(root)

    decisions = [(m.get("timestamp"), rp, m) for rp, m, _ in entries
                 if m.get("type") == "decision"]
    lines = [MARKER + "# All decisions", ""]
    for ts, rp, m in sorted(decisions, key=lambda t: str(t[0] or ""), reverse=True):
        lines.append(f"- {ts} · {_line(rp, m)[2:]}")
    built["views/decisions.md"] = "\n".join(lines) + "\n"

    questions = [(rp, m) for rp, m, _ in entries
                 if m.get("type") == "question" and m.get("status") == "open"]
    lines = [MARKER + "# Open questions", ""]
    for rp, m in sorted(questions):
        lines.append(_line(rp, m))
    built["views/open-questions.md"] = "\n".join(lines) + "\n"

    jira = URI_PATTERNS["redhat.atlassian.net"]
    rows = []
    for rp, m, _ in entries:
        res = str(m.get("resource", ""))
        if jira.match(res):
            rows.append(f"- {res.rsplit('/', 1)[-1]} → [{_title(m, rp)}]({rp})")
    built["views/jira-map.md"] = "\n".join([MARKER + "# Jira map", ""] + sorted(rows)) + "\n"

    people = [(rp, m) for rp, m, _ in entries if m.get("type") == "person"]
    lines = [MARKER + "# People & stakeholders", ""]
    for rp, m in sorted(people):
        feature = rp.split("/")[2]
        lines.append(f"- {feature} · [{_title(m, rp)}]({rp}) — {m.get('role', '')}, "
                     f"{m.get('org', '')} — {m.get('description', '')}")
    built["views/people.md"] = "\n".join(lines) + "\n"

    stale_rows = []
    mem_files = []
    if (mem / "profiles").is_dir():
        mem_files += [("profile", p) for p in sorted((mem / "profiles").glob("*.md"))]
    if (mem / "facts").is_dir():
        mem_files += [("fact", p) for p in sorted((mem / "facts").glob("*.md"))]
    for kind, p in mem_files:
        meta = _meta_of(p)
        if not meta or meta.get("status") == "superseded":
            continue
        rootpath = "/" + p.relative_to(root).as_posix()
        review = _date(meta.get("review_after"))
        ts = _date(meta.get("timestamp"))
        limit = cfg["profile_default_days"] if kind == "profile" else cfg["fact_default_days"]
        overdue = (review and review < today) or (
            not review and ts and (today - ts).days > limit)
        if overdue:
            age = (today - ts).days if ts else "?"
            stale_rows.append(f"- {rootpath} — {meta.get('description', '')} (age {age}d)")
    for rp, m, _ in entries:
        if m.get("type") == "fact" and m.get("status") != "superseded":
            ts = _date(m.get("timestamp"))
            if ts and (today - ts).days > cfg["fact_default_days"]:
                stale_rows.append(f"- {rp} — {m.get('description', '')} "
                                  f"(age {(today - ts).days}d)")
    built["views/stale-facts.md"] = \
        "\n".join([MARKER + "# Stale facts & profiles", ""] + sorted(stale_rows)) + "\n"

    return built


def write_all(root, today=None):
    root = Path(root)
    written = []
    for rel, content in sorted(build_all(root, today).items()):
        path = root / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        with open(path, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(content)
        written.append(rel)
    return written


def check(root, today=None):
    root = Path(root)
    stale = []
    for rel, content in sorted(build_all(root, today).items()):
        path = root / rel
        if not path.is_file() or \
                path.read_text(encoding="utf-8").replace("\r\n", "\n") != content:
            stale.append(rel)
    return stale
