"""Deterministic generation of all index.md files and views/ from frontmatter."""
import datetime
from pathlib import Path

import yaml

from . import frontmatter
from .schema import RESERVED, URI_PATTERNS

MARKER = "<!-- generated by scripts/hub_index.py — do not hand-edit -->\n"


def _load_entries(root, subdir_glob, base="features"):
    """Yield (rootpath, meta, body) for knowledge entries matching the glob."""
    basedir = root / base
    if not basedir.is_dir():
        return
    for entry in sorted(basedir.glob(subdir_glob)):
        if entry.name in RESERVED or not entry.is_file():
            continue
        try:
            meta, body = frontmatter.load_file(entry)
        except frontmatter.FrontmatterError:
            continue  # lint reports this; indexes skip unparseable files
        yield "/" + entry.relative_to(root).as_posix(), meta, body


def _title(meta, rootpath):
    return meta.get("title") or Path(rootpath).stem


def _line(rootpath, meta):
    return f"- [{_title(meta, rootpath)}]({rootpath}) — {meta.get('description', '')}"


def _home(rootpath):
    """Group label for an entry: its feature id, or 'narrative'."""
    parts = rootpath.split("/")
    return parts[2] if parts[1] == "features" else parts[1]


def _date(value):
    try:
        return datetime.date.fromisoformat(str(value))
    except (TypeError, ValueError):
        return None


def _staleness_config(root):
    cfg = {"profile_default_days": 30, "fact_default_days": 90}
    p = root / "conventions" / "staleness.yaml"
    if p.is_file():
        loaded = yaml.safe_load(p.read_text(encoding="utf-8")) or {}
        cfg.update({k: v for k, v in loaded.items() if k in cfg})
    return cfg


def _features_table(root):
    p = root / "features" / "features.yaml"
    if not p.is_file():
        return []
    data = yaml.safe_load(p.read_text(encoding="utf-8")) or {}
    return data.get("features") or []


def _meta_of(path):
    try:
        return frontmatter.load_file(path)[0]
    except frontmatter.FrontmatterError:
        return None


def _load_artifacts(root):
    """Yield (rootpath, meta) for enablement artifact descriptors."""
    for pattern in ("features/*/enablement/*/artifact.md",
                    "narrative/enablement/*/artifact.md"):
        for desc in sorted(root.glob(pattern)):
            meta = _meta_of(desc)
            if meta:
                yield "/" + desc.relative_to(root).as_posix(), meta


def build_all(root, today=None):
    root = Path(root)
    today = today or datetime.date.today()
    built = {}
    feats = _features_table(root)
    entries = list(_load_entries(root, "*/knowledge/*.md"))
    entries += list(_load_entries(root, "knowledge/*.md", base="narrative"))

    artifacts = list(_load_artifacts(root))
    # connection axis (spec D13): features: declarations → per-feature backlinks
    connections = {}
    for rp, m, _ in entries:
        for fid in (m.get("features") or []):
            connections.setdefault(fid, []).append((rp, m))
    for rp, m in artifacts:
        for fid in (m.get("features") or []):
            connections.setdefault(fid, []).append((rp, m))

    # features/index.md
    lines = [MARKER + "# Features", ""]
    for f in feats:
        lines.append(f"- [{f.get('title', f['id'])}](/features/{f['id']}/index.md)"
                     f" — {f.get('description', '')}")
    if not feats:
        lines.append("_No feature partitions yet — hub.file creates them on first use._")
    built["features/index.md"] = "\n".join(lines) + "\n"

    # per-feature indexes (only for partitions that exist on disk)
    for f in feats:
        fdir = root / "features" / f["id"]
        if not fdir.is_dir():
            continue
        lines = [MARKER + f"# {f.get('title', f['id'])}", "", f.get("description", ""), ""]
        for sub in ("knowledge", "research", "strategy", "enablement", "work"):
            lines.append(f"- [{sub}/](/features/{f['id']}/{sub}/)")
        conns = [(rp, m) for rp, m in connections.get(f["id"], [])
                 if not rp.startswith(f"/features/{f['id']}/")]
        if conns:
            lines.append("")
            lines.append("## Connections")
            for rp, m in sorted(conns):
                lines.append(f"- {m.get('type', '?')} · {_line(rp, m)[2:]}")
        built[f"features/{f['id']}/index.md"] = "\n".join(lines) + "\n"

        if (fdir / "knowledge").is_dir():
            lines = [MARKER + f"# {f.get('title', f['id'])} — knowledge", ""]
            by_type = {}
            for rootpath, meta, _ in _load_entries(root, f"{f['id']}/knowledge/*.md"):
                by_type.setdefault(meta.get("type", "other"), []).append((rootpath, meta))
            for etype in sorted(by_type):
                lines.append(f"## {etype}")
                for rootpath, meta in sorted(by_type[etype]):
                    lines.append(_line(rootpath, meta))
                lines.append("")
            built[f"features/{f['id']}/knowledge/index.md"] = \
                "\n".join(lines).rstrip("\n") + "\n"

    # memory/index.md
    mem = root / "memory"
    lines = [MARKER + "# Memory index", "",
             "> Always read this first. Regenerate with `python scripts/hub_index.py`.", ""]
    profiles = sorted((mem / "profiles").glob("*.md")) if (mem / "profiles").is_dir() else []
    if profiles:
        lines.append("## Profiles (current state)")
        for p in profiles:
            meta = _meta_of(p)
            if meta:
                lines.append(f"- [{p.stem}](/{p.relative_to(root).as_posix()})"
                             f" — {meta.get('description', '')}")
        lines.append("")
    facts = sorted((mem / "facts").glob("*.md")) if (mem / "facts").is_dir() else []
    fact_metas = [( "/" + p.relative_to(root).as_posix(), _meta_of(p))
                  for p in facts if _meta_of(p)]
    fact_metas.sort(key=lambda t: str(t[1].get("timestamp", "")), reverse=True)
    if fact_metas:
        lines.append("## Recent facts")
        for rootpath, meta in fact_metas[:10]:
            lines.append(f"- [{Path(rootpath).stem}]({rootpath}) — {meta.get('description', '')}")
        lines.append("")
    log = mem / "log.md"
    if log.is_file():
        _, body = frontmatter.load_file(log)
        lines.append("## Recent log")
        current, shown = None, 0
        for raw in body.splitlines():
            if raw.startswith("## "):
                current = raw[3:].strip()
            elif raw.startswith("- ") and current and shown < 5:
                lines.append(f"- {current} — {raw[2:].strip()}")
                shown += 1
        lines.append("")
    built["memory/index.md"] = "\n".join(lines).rstrip("\n") + "\n"

    # narrative/ indexes (only when the layer exists on disk)
    ndir = root / "narrative"
    if ndir.is_dir():
        lines = [MARKER + "# Narrative", "",
                 "The story layer: pillars, cross-feature stories, and the "
                 "strategy spine.", ""]
        for sub in ("knowledge", "research", "strategy", "enablement", "work"):
            lines.append(f"- [{sub}/](/narrative/{sub}/)")
        built["narrative/index.md"] = "\n".join(lines) + "\n"
        if (ndir / "knowledge").is_dir():
            lines = [MARKER + "# Narrative — knowledge", ""]
            by_type = {}
            for rootpath, meta, _ in _load_entries(root, "knowledge/*.md",
                                                   base="narrative"):
                by_type.setdefault(meta.get("type", "other"), []).append(
                    (rootpath, meta))
            for etype in sorted(by_type):
                lines.append(f"## {etype}")
                for rootpath, meta in sorted(by_type[etype]):
                    lines.append(_line(rootpath, meta))
                lines.append("")
            built["narrative/knowledge/index.md"] = \
                "\n".join(lines).rstrip("\n") + "\n"

    # views/
    cfg = _staleness_config(root)

    decisions = [(m.get("timestamp"), rp, m) for rp, m, _ in entries
                 if m.get("type") == "decision"]
    lines = [MARKER + "# All decisions", ""]
    for ts, rp, m in sorted(decisions, key=lambda t: str(t[0] or ""), reverse=True):
        lines.append(f"- {ts} · {_line(rp, m)[2:]}")
    built["views/decisions.md"] = "\n".join(lines) + "\n"

    questions = [(rp, m) for rp, m, _ in entries
                 if m.get("type") == "question" and m.get("status") == "open"]
    lines = [MARKER + "# Open questions", ""]
    for rp, m in sorted(questions):
        lines.append(_line(rp, m))
    built["views/open-questions.md"] = "\n".join(lines) + "\n"

    jira = URI_PATTERNS["redhat.atlassian.net"]
    rows = []
    for rp, m, _ in entries:
        res = str(m.get("resource", ""))
        if jira.match(res):
            rows.append(f"- {res.rsplit('/', 1)[-1]} → [{_title(m, rp)}]({rp})")
    built["views/jira-map.md"] = "\n".join([MARKER + "# Jira map", ""] + sorted(rows)) + "\n"

    people = [(rp, m) for rp, m, _ in entries if m.get("type") == "person"]
    lines = [MARKER + "# People & stakeholders", ""]
    for rp, m in sorted(people):
        feature = _home(rp)
        lines.append(f"- {feature} · [{_title(m, rp)}]({rp}) — {m.get('role', '')}, "
                     f"{m.get('org', '')} — {m.get('description', '')}")
    built["views/people.md"] = "\n".join(lines) + "\n"

    stale_rows = []
    mem_files = []
    if (mem / "profiles").is_dir():
        mem_files += [("profile", p) for p in sorted((mem / "profiles").glob("*.md"))]
    if (mem / "facts").is_dir():
        mem_files += [("fact", p) for p in sorted((mem / "facts").glob("*.md"))]
    for kind, p in mem_files:
        meta = _meta_of(p)
        if not meta or meta.get("status") == "superseded":
            continue
        rootpath = "/" + p.relative_to(root).as_posix()
        review = _date(meta.get("review_after"))
        ts = _date(meta.get("timestamp"))
        limit = cfg["profile_default_days"] if kind == "profile" else cfg["fact_default_days"]
        overdue = (review and review < today) or (
            not review and ts and (today - ts).days > limit)
        if overdue:
            age = (today - ts).days if ts else "?"
            stale_rows.append(f"- {rootpath} — {meta.get('description', '')} (age {age}d)")
    for rp, m, _ in entries:
        if m.get("type") == "fact" and m.get("status") != "superseded":
            ts = _date(m.get("timestamp"))
            if ts and (today - ts).days > cfg["fact_default_days"]:
                stale_rows.append(f"- {rp} — {m.get('description', '')} "
                                  f"(age {(today - ts).days}d)")
    for rp, m, _ in entries:
        if m.get("type") in ("qa", "jtbd"):
            review = _date(m.get("review_after"))
            if review and review < today:
                stale_rows.append(f"- {rp} — {m.get('description', '')} "
                                  f"(review overdue)")
    built["views/stale-facts.md"] = \
        "\n".join([MARKER + "# Stale facts & profiles", ""] + sorted(stale_rows)) + "\n"

    # views/narrative-map.md — pillars → stories → features (spec §6)
    pillars = sorted([(rp, m) for rp, m, _ in entries if m.get("type") == "pillar"])
    stories = sorted([(rp, m) for rp, m, _ in entries if m.get("type") == "story"])
    lines = [MARKER + "# Narrative map", ""]
    used = set()
    for prp, pm in pillars:
        lines.append(f"## [{_title(pm, prp)}]({prp})")
        lines.append(pm.get("description", ""))
        owned = [(rp, m) for rp, m in stories if m.get("pillar") == prp]
        for rp, m in owned:
            used.add(rp)
            lines.append(f"- [{_title(m, rp)}]({rp}) — {m.get('description', '')}")
            feats_str = ", ".join(f"[{fid}](/features/{fid}/index.md)"
                                  for fid in (m.get("features") or []))
            if feats_str:
                lines.append(f"  - connects: {feats_str}")
        if not owned:
            lines.append("- _no stories yet_")
        lines.append("")
    orphans = [(rp, m) for rp, m in stories if rp not in used]
    if orphans:
        lines.append("## Stories without a pillar")
        for rp, m in orphans:
            lines.append(_line(rp, m))
        lines.append("")
    built["views/narrative-map.md"] = "\n".join(lines).rstrip("\n") + "\n"

    # views/faq.md — the field Q&A rollup ("FAQ" is the audience-facing name)
    qas = [(rp, m) for rp, m, _ in entries if m.get("type") == "qa"]

    def _ask_count(m):
        asks = m.get("asks")
        return len(asks) if isinstance(asks, list) else 0

    lines = [MARKER + "# FAQ — field questions & answers", ""]
    unanswered = sorted([(rp, m) for rp, m in qas if m.get("status") == "open"],
                        key=lambda t: str(t[1].get("timestamp", "")), reverse=True)
    if unanswered:
        lines.append("## Unanswered")
        for rp, m in unanswered:
            lines.append(f"- {_line(rp, m)[2:]} (asked {_ask_count(m)}x)")
        lines.append("")
    recurring = sorted([(rp, m) for rp, m in qas if _ask_count(m) >= 2],
                       key=lambda t: (-_ask_count(t[1]), t[0]))
    if recurring:
        lines.append("## Most asked")
        for rp, m in recurring:
            lines.append(f"- {_ask_count(m)}x · {_line(rp, m)[2:]}")
        lines.append("")
    by_home = {}
    for rp, m in qas:
        by_home.setdefault(_home(rp), []).append((rp, m))
    if by_home:
        lines.append("## All, by home")
        for home in sorted(by_home):
            lines.append(f"### {home}")
            for rp, m in sorted(by_home[home]):
                lines.append(_line(rp, m))
            lines.append("")
    built["views/faq.md"] = "\n".join(lines).rstrip("\n") + "\n"

    # views/jtbd.md — jobs by status, evidence-count flagged (spec §6, D15)
    jtbds = [(rp, m) for rp, m, _ in entries if m.get("type") == "jtbd"]
    lines = [MARKER + "# Jobs to be done", ""]
    for status in ("candidate", "validated", "delivered", "retired"):
        group = sorted([(rp, m) for rp, m in jtbds if m.get("status") == status])
        if not group:
            continue
        lines.append(f"## {status}")
        for rp, m in group:
            ev = m.get("evidence")
            ev_n = len(ev) if isinstance(ev, list) else 0
            ev_str = f"{ev_n} evidence" if ev_n else "NO EVIDENCE"
            jira = f" · {m['jira']}" if m.get("jira") else ""
            lines.append(f"- {_home(rp)} · persona: {m.get('persona', '?')} · "
                         f"{ev_str}{jira} · {_line(rp, m)[2:]}")
        lines.append("")
    built["views/jtbd.md"] = "\n".join(lines).rstrip("\n") + "\n"

    # views/artifacts.md — every enablement artifact; publish state from manifest
    manifest_dest = {}
    mpath = root / "publish" / "manifest.yaml"
    if mpath.is_file():
        try:
            for e in (yaml.safe_load(mpath.read_text(encoding="utf-8")) or []):
                if isinstance(e, dict) and e.get("source") and e.get("dest"):
                    key = str(e["source"]).replace("\\", "/").strip("/")
                    manifest_dest[key] = str(e["dest"])
        except yaml.YAMLError:
            pass
    lines = [MARKER + "# Artifacts", ""]
    slug_dirs = []
    for pattern in ("features/*/enablement/*", "narrative/enablement/*"):
        slug_dirs += [p for p in sorted(root.glob(pattern)) if p.is_dir()]
    for slug in slug_dirs:
        rel = slug.relative_to(root).as_posix()
        desc = _meta_of(slug / "artifact.md") if (slug / "artifact.md").is_file() else None
        pub = manifest_dest.get(rel)
        pub_str = f"published → {pub}" if pub else "unpublished"
        if desc:
            feats = ", ".join(desc.get("features") or [])
            feat_str = f" · connects: {feats}" if feats else ""
            lines.append(f"- [{desc.get('title') or slug.name}](/{rel}/) — "
                         f"{desc.get('description', '')} ({pub_str}){feat_str}")
        else:
            lines.append(f"- [{slug.name}](/{rel}/) — _no artifact.md descriptor "
                         f"yet_ ({pub_str})")
    built["views/artifacts.md"] = "\n".join(lines) + "\n"

    return built


def write_all(root, today=None):
    root = Path(root)
    written = []
    for rel, content in sorted(build_all(root, today).items()):
        path = root / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        with open(path, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(content)
        written.append(rel)
    return written


def check(root, today=None):
    root = Path(root)
    stale = []
    for rel, content in sorted(build_all(root, today).items()):
        if rel == "views/stale-facts.md":
            continue  # time-dependent view: refreshed by reindex runs, not freshness-gated
        path = root / rel
        if not path.is_file() or \
                path.read_text(encoding="utf-8").replace("\r\n", "\n") != content:
            stale.append(rel)
    return stale
