"""The Jira snapshot contract (spec /docs/specs/2026-07-09-jira-hub-skills-design.md):
whitelisted rows, byte-stable YAML, lint validation, sync diffing, and the
ref-/jtbd watched-key scan. Snapshots are machine-written by hub.jira-sweep
into features/<id>/work/jira-snapshot.yaml — tracked, public, never
hand-edited. Only FIELDS ever enter a snapshot; summaries only when the
unauthenticated probe proved the issue world-readable."""
import re
from pathlib import Path

import yaml

from . import frontmatter

MARKER = "# generated by hub.jira-sweep (scripts/hub_jira.py) — do not hand-edit"
SNAPSHOT_GLOB = "features/*/work/jira-snapshot.yaml"
FIELDS = ("key", "type", "status", "resolution", "fix_versions", "updated", "summary")
JIRA_BROWSE_RE = re.compile(
    r"^https://redhat\.atlassian\.net/browse/([A-Z][A-Z0-9]*-\d+)$")


def _key_sort(key):
    proj, _, num = str(key).rpartition("-")
    return (proj, int(num) if num.isdigit() else 0)


def issue_row(issue, public):
    """Whitelist one raw API issue into a snapshot row. `public` comes from
    jira.probe_public — a redacted summary is None, never elided."""
    f = issue.get("fields", {})
    return {
        "key": issue.get("key", ""),
        "type": (f.get("issuetype") or {}).get("name", ""),
        "status": (f.get("status") or {}).get("name", ""),
        "resolution": (f.get("resolution") or {}).get("name"),
        "fix_versions": [v.get("name", "") for v in (f.get("fixVersions") or [])],
        "updated": str(f.get("updated") or "")[:10] or None,
        "summary": (f.get("summary") or "") if public else None,
    }


def build_snapshot(feature_id, jql, rows, swept):
    """Byte-stable snapshot text: same rows -> identical bytes, so diffs are
    reviewable and the jira-map view regenerates deterministically."""
    data = {
        "feature": feature_id,
        "jql": jql,
        "swept": swept,
        "issues": sorted(rows, key=lambda r: _key_sort(r.get("key", ""))),
    }
    return MARKER + "\n" + yaml.safe_dump(
        data, sort_keys=False, allow_unicode=True, default_flow_style=False)


def load_all(root):
    """[(feature_id, data)] for every parseable snapshot, sorted by path.
    Permissive — lint (validate) is where breakage is reported."""
    out = []
    for snap in sorted(Path(root).glob(SNAPSHOT_GLOB)):
        try:
            data = yaml.safe_load(snap.read_text(encoding="utf-8"))
        except yaml.YAMLError:
            continue
        if isinstance(data, dict) and isinstance(data.get("issues"), list):
            out.append((snap.parent.parent.name, data))
    return out


def validate(root):
    """Lint every tracked snapshot. Structural problems are errors — a broken
    snapshot means a broken sweep or a hand edit, and both must fail CI."""
    root = Path(root)
    errors, warnings = [], []
    for snap in sorted(root.glob(SNAPSHOT_GLOB)):
        rel = snap.relative_to(root).as_posix()
        text = snap.read_text(encoding="utf-8")
        if (text.splitlines() or [""])[0] != MARKER:
            errors.append(f"{rel}: missing generated-file marker (snapshots are "
                          f"machine-written by hub.jira-sweep — never by hand)")
        try:
            data = yaml.safe_load(text)
        except yaml.YAMLError as exc:
            errors.append(f"{rel}: invalid YAML: {exc}")
            continue
        if not isinstance(data, dict):
            errors.append(f"{rel}: snapshot must be a mapping")
            continue
        fid = snap.parent.parent.name
        if data.get("feature") != fid:
            errors.append(f"{rel}: feature '{data.get('feature')}' does not match "
                          f"its directory '{fid}'")
        for field in ("jql", "swept"):
            if not data.get(field):
                errors.append(f"{rel}: missing '{field}'")
        issues = data.get("issues")
        if not isinstance(issues, list):
            errors.append(f"{rel}: 'issues' must be a list")
            continue
        for i, row in enumerate(issues):
            if not isinstance(row, dict):
                errors.append(f"{rel}: issue row {i} must be a mapping")
                continue
            for field in ("key", "type", "status"):
                if not row.get(field):
                    errors.append(f"{rel}: issue row {i} missing '{field}'")
    return errors, warnings


def diff(old_rows, new_rows):
    """Pure set/field comparison between two row lists. Returns
    {'new': [rows], 'vanished': [rows], 'changed': [{'key', 'changes'}]}
    where changes maps field -> (old, new)."""
    old = {r["key"]: r for r in old_rows if r.get("key")}
    new = {r["key"]: r for r in new_rows if r.get("key")}
    changed = []
    for key in sorted(old.keys() & new.keys(), key=_key_sort):
        deltas = {f: (old[key].get(f), new[key].get(f))
                  for f in FIELDS if f != "key" and old[key].get(f) != new[key].get(f)}
        if deltas:
            changed.append({"key": key, "changes": deltas})
    return {
        "new": [new[k] for k in sorted(new.keys() - old.keys(), key=_key_sort)],
        "vanished": [old[k] for k in sorted(old.keys() - new.keys(), key=_key_sort)],
        "changed": changed,
    }


def watched_keys(root):
    """Jira keys referenced by tracked entries — ref- resource: URLs and jtbd
    jira: lists — mapped to the rootpaths that reference them. hub.jira-sync
    watches these even outside every stored JQL scope, so refs never
    silently rot."""
    root = Path(root)
    watched = {}

    def scan(glob, base):
        basedir = root / base
        if not basedir.is_dir():
            return
        for entry in sorted(basedir.glob(glob)):
            if not entry.is_file():
                continue
            try:
                meta, _ = frontmatter.load_file(entry)
            except frontmatter.FrontmatterError:
                continue
            rp = "/" + entry.relative_to(root).as_posix()
            keys = []
            m = JIRA_BROWSE_RE.match(str(meta.get("resource", "")))
            if m:
                keys.append(m.group(1))
            if meta.get("type") == "jtbd" and isinstance(meta.get("jira"), list):
                keys.extend(k for k in meta["jira"] if isinstance(k, str))
            for k in keys:
                watched.setdefault(k, []).append(rp)

    scan("*/knowledge/*.md", "features")
    scan("knowledge/*.md", "narrative")
    return watched
